version: "3"
services:
  dev:
    build:
      context: ./
    image: 'thp-dev/ggm'
    volumes:
      - ./:/usr/src/app/
    restart: unless-stopped
    environment:
      - CI_API_V4_URL=https://gitlab.com/api/v4
      - GITLAB_TOKEN=$GITLAB_TOKEN
    working_dir: /usr/src/app
    command: ["sleep", "infinity"]
